branch-defaults:
  master:
    environment: synapse-login-scipoolprod
global:
  application_name: synapse-login
  workspace_type: Application
deploy:
  artifact: target/SynapseAWSConsoleLogin-1.0.war
